version: "3"
services:
  nuxt:
    environment:
      - LOCATION_HOST=127.0.0.1:3333
      - MONGO_LOGIN=asfoASfg35gse
      - MONGO_PASSWORD=sdogo235DSgbseGazb21
      - LOCATION_MODE=local
    build:
      context: .
      dockerfile: Dockerfile_nuxt_prod
    volumes:
      - "./app:/src/app"
    ports:
      - "3333:3333"
